version: '3.1'
services:
  mysql:
    container_name: openstad_notification_db
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "openstad_notification"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - database:/var/lib/mysql
    networks:
      - openstad

  app:
    environment:
      ENVIRONMENT: "development"
      DB_PORT: "3306"
      DB_HOST: "openstad_notification_db"
      DB_USER: "root"
      DB_PASSWORD: "root"
      DB_NAME: "openstad_notification"
    volumes:
      - ./image/images:/app/images
    build: .
    ports:
      - 9090:9090
    expose:
      - 9090
    restart: unless-stopped
    networks:
      - openstad
    depends_on:
      - "mysql"
    command: npm run start

volumes:
  database:
networks:
  openstad:
    external: true
