version: '3.1'
services:
  mysql:
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_ROOT_DATABASE}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    expose:
      - "3306"
      - "33060"
    restart: unless-stopped
    ports:
      - "3310:3306"
    entrypoint:
      sh -c "
      echo 'CREATE DATABASE IF NOT EXISTS ${AUTH_DB_NAME}; CREATE DATABASE IF NOT EXISTS ${IMAGE_DB_NAME}; CREATE DATABASE IF NOT EXISTS ${API_DATABASE};' > /docker-entrypoint-initdb.d/init.sql;
      /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    volumes:
      - database:/var/lib/mysql
    networks:
      - database

  image:
    build: image
    environment:
      ENVIRONMENT: "development"
      PORT_API: "${IMAGE_PORT_API}"
      PORT_IMAGE_SERVER: "${IMAGE_PORT_STEAM}"
      APP_URL: "${IMAGE_APP_URL}"
      #needs to best to network name in depends_on of mysql
      DB_HOST: "${MYSQL_HOST}"
      DB_USER: "root"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      DB_NAME: "${IMAGE_DB_NAME}"
    volumes:
      - ./image/images:/app/images
    ports:
      - ${IMAGE_PORT_API}:${IMAGE_PORT_API}
    restart: unless-stopped
    networks:
      - database
    depends_on:
      - "mysql"
